dist: xenial

sudo: required

group: edge

language: php

env:
  global:
      - COMPOSER_UPDATE="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
      - COMPOSER_CONFIG="--global github-oauth.github.com b7244dc99194b22416d5ce46d511ce04049b23de"

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: "7.4"
      env:
        - DB=pgsql
        - DB=mysql
        - DB=sqlite
      services:
        - postgresql
        - mysql

    - php: "7.3"
      env:
        - DB=pgsql
        - DB=mysql
        - DB=sqlite
      services:
        - postgresql
        - mysql

    - php: "7.2"
      env:
        - DB=pgsql
        - DB=mysql
        - DB=sqlite
      services:
        - postgresql
        - mysql

    - php: "7.1"
      env:
        - DB=pgsql
        - DB=mysql
        - DB=sqlite
      services:
        - postgresql
        - mysql

    - php: "7.0"
      env:
        - DB=pgsql
        - DB=mysql
        - DB=sqlite
      services:
        - postgresql
        - mysql

    - php: "5.6"
      env:
        - DB=pgsql
        - DB=mysql
        - DB=sqlite
      services:
        - postgresql
        - mysql

    - php: "5.5"
      dist: trusty
      env:
        - DB=pgsql
        - DB=mysql
        - DB=sqlite
      services:
        - postgresql
        - mysql

    - php: "5.4"
      dist: trusty
      env:
        - DB=pgsql
        - DB=mysql
        - DB=sqlite
      services:
        - postgresql
        - mysql

addons:
  hosts:
    - basic.cetver-yii2-routes-collector
    - frontend.cetver-yii2-routes-collector
    - backend.cetver-yii2-routes-collector

install:
  - sudo apt-get install nginx
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer config $COMPOSER_CONFIG
  - travis_retry composer update $COMPOSER_UPDATE

before_script:
  # php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ $(phpenv version-name | cut -c 1) == "7" ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # nginx
  - sudo cp travis-ci-nginx.conf /etc/nginx/sites-enabled/cetver-yii2-routes-collector.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/nginx/sites-enabled/cetver-yii2-routes-collector.conf
  - sudo nginx -t
  - sudo service nginx restart
  # DBs
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE \"cetver-yii2-routes-collector\";' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE \`cetver-yii2-routes-collector\`;' -u root; fi"

script:
   - vendor/bin/codecept run unit,functional --coverage-xml
   - vendor/bin/coveralls
