dist: trusty

sudo: required

language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

services:
  - postgresql
  - mysql

env:
  - DB=pgsql
  - DB=mysql
  - DB=sqlite

addons:
  hosts:
    - basic.cetver-yii2-routes-collector
    - frontend.cetver-yii2-routes-collector
    - backend.cetver-yii2-routes-collector

install:
  - sudo apt-get install nginx
  # avoids errors like "Failed to clone the git@github.com:twbs/bootstrap.git repository,
  # try running in interactive mode so that you can enter your GitHub credentials"
  - composer config --global github-oauth.github.com b7244dc99194b22416d5ce46d511ce04049b23de
  - composer global require "fxp/composer-asset-plugin:~1.3.1"
  - composer update --prefer-dist --no-interaction

before_script:
  # php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ $(phpenv version-name | cut -c 1) == "7" ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # nginx
  - sudo cp travis-ci-nginx.conf /etc/nginx/sites-enabled/cetver-yii2-routes-collector.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/nginx/sites-enabled/cetver-yii2-routes-collector.conf
  - sudo nginx -t
  - sudo service nginx restart
  # DBs
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE \"cetver-yii2-routes-collector\";' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE \`cetver-yii2-routes-collector\`;' -u root; fi"

script:
   - vendor/bin/codecept run unit,functional --coverage-xml
   - vendor/bin/coveralls

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache